### ISSUE TITLE
Documentation in archive is generated?

### ISSUE THREAD

**Issue by gbraad** [McYoloSwagHam/win3wm#1]
Can you publish documentation in a human-readable form without the use of tools, like a browser?
It feels like the current `./docs` is a dump of generated files that are to be included in the release package.

**Comment by McYoloSwagHam** [comment]
the github pages for this project, over at [mcyoloswagham.github.io/win3wm](https://mcyoloswagham.github.io/win3wm) pulls it resources from the docs folder, would it help if I changed the name of the folder

**Comment by gbraad** [comment]
I was looking for 'docs' to make a decision if this is what I 'need'. it would still be nice if a markdown, asciidoc, or plain format is available. Although, knowing this link makes it easier; ... but please link to it

**Comment by McYoloSwagHam** [comment]
There was a link to the website under the **Manual** header in the Readme on the word "here", though I have now added documentation as a header, to make it more clear.
