### ISSUE TITLE
Error: QueryService VDM: 14007

### ISSUE THREAD

**Issue by origamidance** [McYoloSwagHam/win3wm#16]
I successfully built the executable, but when running it, I got a dialog window saying: Error: QueryService VDM: 14007.
![image](https://user-images.githubusercontent.com/15731474/110363113-712e7900-8042-11eb-814b-b6c760d6015b.png)

Any idea on what's wrong with my setup?

**Comment by origamidance** [comment]
My system version is: Insider 21327

**Comment by McYoloSwagHam** [comment]
so due the private COM Api, I have to put in version checks for each version, last version was 21322, I'll add 21327 soon.

**Comment by McYoloSwagHam** [comment]
I've added support, uptil 21382, and will keep up to date
