### ISSUE TITLE
Program start error: "Couldn't allocate memory for error print"

### ISSUE THREAD

**Issue by imlukedewitt** [McYoloSwagHam/win3wm#17]
Hello, Launching WinWM results in the following error popup:
![image](https://user-images.githubusercontent.com/45362944/111910649-8383bc00-8a1f-11eb-9f5a-3befbbb448a4.png)

I've whitelisted the WinWM folder from Defender, and installed the latest C++ 2015-2019 Redistritibutable.
![image](https://user-images.githubusercontent.com/45362944/111910743-db222780-8a1f-11eb-92d1-200e862eb758.png)

Hovering over the WinWM taskbar icon results in the following error, which doesn't seem like the main issue, but I'm including it just in case it's helpful:
![image](https://user-images.githubusercontent.com/45362944/111910794-0d338980-8a20-11eb-8025-7504720b7c15.png)

For reference I'm running Windows 10 20H2 x64. 

Any assistance would be greatly appreciated!

**Comment by McYoloSwagHam** [comment]
Hi Luke,  I'm a bit busy, but could you set the logs options in config to "y", it's called "enable_logs", remove any personalized information in windows names and then upload the text?

**Comment by imlukedewitt** [comment]
So sorry for the delay in response. I'm no longer able to recreate this error! 

I tried several combinations a week ago and couldn't get WinWM to work, and now I've tried several combinations and I can't get it to break. No clue what might have changed, I'm using a new (ish) Windows installation so it's possible an update fixed a dependency.
