### ISSUE TITLE
Cannot maintain focus on dialog boxes, which makes win3wm unusable

### ISSUE THREAD

**Issue by blokeley** [McYoloSwagHam/win3wm#18]
To replicate:

1. Start WinWM.exe
2. Start almost any program that runs on Windows e.g. Notepad
3. In notepad, invoke the Open File command.

win3wm forces focus to return immediately to the main notepad window, which means that I cannot use the dialog and notepad is unusable.  The same issue happens with any program with a modal dialog box (which is almost all Windows programs).

**Comment by OlympusMonds** [comment]
In your config.json, change the force focus to be 'n'.

It's this line here: https://github.com/McYoloSwagHam/win3wm/blob/e50cf7f38da0221ede99e1148ebd8d19397b1ed3/Build/config.json#L61

**Comment by blokeley** [comment]
That fixed the dialog focus problem thank you.  I don't know how people can use win3wm if dialog boxes are rendered unusable so perhaps the default should be "n".  

Now the problem is that the task switcher (Alt-Tab) loses focus within a second so is unusable (I have my win2wm modifier set to "wIn").  I guess win3wm users are supposed to use the win3wm keyboard shortcuts to switch between focussed windows rather than Alt-Tab.

**Comment by McYoloSwagHam** [comment]
I've changed the default to "n", if you have force_focus disabled, the alt tab also won't disappear
