### ISSUE TITLE
Lossless compression of PNG assets

### ISSUE THREAD

**Issue by JackBender** [McYoloSwagHam/win3wm#2]
Hi,

Using the windows program _PNGGauntlet_, PNG images can be losslessly further compressed.
The worst recompression yields 81% of original image size, and in the best case the new image is only 35% the size of the original one.

![showcase_1](https://user-images.githubusercontent.com/7989192/109432231-96036a80-7a0a-11eb-80a3-4eb04d43780e.png)
![showcase_2](https://user-images.githubusercontent.com/7989192/109432232-969c0100-7a0a-11eb-9256-8b41fb0908fd.png)
![favicon](https://user-images.githubusercontent.com/7989192/109432234-97349780-7a0a-11eb-8bf7-4372feaaaca1.png)
![diag](https://user-images.githubusercontent.com/7989192/109432235-97349780-7a0a-11eb-9123-74d33755d368.png)
![dsp](https://user-images.githubusercontent.com/7989192/109432236-97cd2e00-7a0a-11eb-9db3-ed7f9008ca2a.png)
![ex1](https://user-images.githubusercontent.com/7989192/109432237-97cd2e00-7a0a-11eb-928e-ea45822fd7b5.png)
![ex2](https://user-images.githubusercontent.com/7989192/109432238-97cd2e00-7a0a-11eb-9a3e-12c4eaf6fbde.png)
![mtnew](https://user-images.githubusercontent.com/7989192/109432239-9865c480-7a0a-11eb-91ad-404ae3d24bc3.png)
![mtregroup](https://user-images.githubusercontent.com/7989192/109432241-9865c480-7a0a-11eb-8c6d-f0c560908f79.png)
![mtstart](https://user-images.githubusercontent.com/7989192/109432242-9865c480-7a0a-11eb-8be0-0971cc99b84d.png)
![mtswitch](https://user-images.githubusercontent.com/7989192/109432243-98fe5b00-7a0a-11eb-9daf-c40a3ac9e90a.png)

**Comment by McYoloSwagHam** [comment]
Thanks for the advice, will take it consideration in the future.
