### ISSUE TITLE
Win3WMServer did not signal event

### ISSUE THREAD

**Issue by jiywww** [McYoloSwagHam/win3wm#20]
## description
I failed to start the Win3wm. It was working fine when I first time run it but cannot be started again after I exit and reopen it and show the error as the screenshot below.
![image](https://user-images.githubusercontent.com/57605947/117579333-4d42ee80-b0ea-11eb-994a-0a0c064f736c.png)

## Hardware Environment
- Three monitors
    - Laptop built-in monitor with 1920 * 1080 and 100% scale.
    - 3440 * 1440 monitor with 100% scale
    - 1920 * 1080 monitor with 100% scale
## Software Environment
- OS: Windows 10 Pro
- OS version: 20H2
- OS build: 19042.928
## Log
Display (10003) RSW : 1920 RSH : 1040
Display (10001) RSW : 3440 RSH : 1400
Display (10005) RSW : 1920 RSH : 1040
Gathering Initial Windows
Gathered Window :
	[WindowClass] : CabinetWClass
	[WindowText] : WinWM
Gathered Window :
	[WindowClass] : Chrome_WidgetWin_1
	[WindowText] : config.json - Visual Studio Code
Gathered Window :
	[WindowClass] : Chrome_WidgetWin_1
	[WindowText] : outer_gaps_vertical cannot be bigger than screen height  Issue #3  McYoloSwagHam/win3wm and 10 more pages - Personal - MicrosoftGathered Window :
	[WindowClass] : CabinetWClass
	[WindowText] : File Explorer
Gathered Window :
	[WindowClass] : HwndWrapper[TickTick.exe;;bfa9b6ce-e1d8-4004-bfe9-cbfb840675d0]
	[WindowText] : OnNewWindow : 37C0
Ignoring Window : 37C0
OnNewWindow : 0
Ignoring Window : 0

**Comment by McYoloSwagHam** [comment]
So I'm not really sure what caused this, but my suspicion is that the x86 server didn't die, and it was already occupying the pipe.
so the next time you started the program it silently died and couldn't resolve the connection since the named pipe was occupied.

to resolve this issue, if you see the problem happening, go to task manager and then to details, and kill x86ipc.exe and try starting win3wm again.

**Comment by jiywww** [comment]
> So I'm not really sure what caused this, but my suspicion is that the x86 server didn't die, and it was already occupying the pipe.
> so the next time you started the program it silently died and couldn't resolve the connection since the named pipe was occupied.
> 
> to resolve this issue, if you see the problem happening, go to task manager and then to details, check if x86ipc.exe is a process and if it is then kill it, and try start win3wm again.

Thank you for your help. I cannot find the x86ipc.exe in the task manager, but the problem was resolved today automatically. I guess I just need to restart my pc to fix the issue. However, I am doing some work and not be able to restart the pc, I will verify it later today.

**Comment by McYoloSwagHam** [comment]
I haven't been able to reproduce this issue even exiting the program with the taskbar icon
