### ISSUE TITLE
issue: cannot work with utools

### ISSUE THREAD

**Issue by jiywww** [McYoloSwagHam/win3wm#21]
- I noticed that the Win3wm cannot work with spotlight-like software such as utools and Powertoys Run. The input bar could appear but disappear immediately. I have not tested other similar software, but I do no think they could work.

- Also, the right-click menu of the taskbar icons of many software does not work when running the Win3wm. The menus do appear but disappear immediately.

Could you please consider fixing this issue? It is really important for the usability of the Win3wm. Thank you very much.

**Comment by McYoloSwagHam** [comment]
Hi, win3wm has the ability to ignore windows in the config.json, just add the powertoys run window there
also you an turn off WinWMs default to force the focus onto the current window, it was recently changed in a patch
just change "force_focus" to "n"
