### ISSUE TITLE
Error QueryService VDM : 14007

### ISSUE THREAD

**Issue by NotYetHAX** [McYoloSwagHam/win3wm#23]
![image](https://user-images.githubusercontent.com/81165187/123541372-e1c1e880-d74c-11eb-95f4-ca3fa1cf97ff.png)
(Latest release)
Is there any solution for this error?

**Comment by McYoloSwagHam** [comment]
Ok I've pushed the fix, I'm not running the latest insider so I have no idea if the windows interface (API) has changed, I'm gonna leave this open just incase stuff is wonky, otherwise feel free to close it.

[https://github.com/McYoloSwagHam/win3wm/actions/runs/976344079](the compiled action)

**Comment by Yusuf007R** [comment]
im having this error in the latest release any idea why?

**Comment by cmprmsd** [comment]
I also have this issue on the latest release called "spacing".

**Comment by leetschau** [comment]
I downloaded the latest release and have the same issue on Windows 11.
