### ISSUE TITLE
Installation error: MSbuild is not recognized as internal or external command

### ISSUE THREAD

**Issue by oren** [McYoloSwagHam/win3wm#4]
Context: I am not familiar with the windows command prompt. I only use WSL (Windows Subsystem for Linux).

Step to reproduce:
1. hit the window key
2. type command prompt
3. git clone https://github.com/McYoloSwagHam/win3wm
4. cd win3wm
5. start build.bat

Results:
new terminal was opened with a few errors like this: MSbuild is not recognized as internal or external command. 

Note: I noticed that the readme mentioned VSStudio. Do I have to install it? If so, can you provide steps for windows newb like me?

Thanks!

**Comment by McYoloSwagHam** [comment]
yeah sure, so you have to install visual studio, install the C++ and Windows C++ extensions.
then there should be a specific command prompt you can find, called "Developer Command Prompt for VS 2019" run that and navigate to win3wm.
then just running build.bat should work

**Comment by oren** [comment]
is it free? can I use https://visualstudio.microsoft.com/vs/community/?

**Comment by oren** [comment]
i installed it and i see 'extension' menu item. i clicked on it and searched for 'C++'. i see a lot of options. which one do i need to choose?

**Comment by McYoloSwagHam** [comment]
Tools -> Get Tools and Features.
Desktop Development with C++, install that and you should be able to build it

**Comment by Nampuk** [comment]
If you're installing VisalStudio 'Desktop developement with C++' should do the trick.
If its just the build tools 'C++ Buildtools' is probably the right call.
It works with 'Desktop developement with C++' (on my machine)

**Comment by oren** [comment]
Thank you! I installed 'Desktop Development with C++'.

I am following [this stackoverflow answer](https://stackoverflow.com/a/28589035) to build the project:

1. Right click the batch file in the Solution Explorer
1. Select “Open With…” from the context menu
1. Click “Add…”
1. In the “Program name” textbox, enter powershell.exe
1. In the “Friendly name” textbox enter “PowerShell”
1. Select “Set As Default
1. Click OK

a blue window is opened for a second and closes. I am looking inside the build folder but I don't see an executable.
