### ISSUE TITLE
Dependency on debug version of library MSVCP140D.dll

### ISSUE THREAD

**Issue by ChristopherL-STCU** [McYoloSwagHam/win3wm#7]
When I try to run the application I receive the error:

> The code execution cannot proceed because MSVCP140D.dll was not found. Reinstalling the program may fix this problem.

Apparently the ['D' suffix implies the debug version of the library is being referenced](https://stackoverflow.com/a/51438071/16973). Referencing the release version will make the application more accessible to others.

**Comment by jasonparekh** [comment]
FYI looks like just 1.0.2 was built against the debug DLLs. 1.0.1 seems fine.

**Comment by ChristopherL-STCU** [comment]
Thanks. That is the version I downloaded. I tried downloading and running that version again. I still receive the same error.

**Comment by Menn1s** [comment]
If you have the space for it and don't mind, just install visual studio community edition. Found pretty much the same information on my search and that ended up providing all the debugging dlls

**Comment by McYoloSwagHam** [comment]
I've released a new version, and tested it on a clean machine, everything seems to run, maybe I compiled v1.0.2 in debug mode, if so my bad. Please close this issue or reply if the newest version runs fine

**Comment by ChristopherL-STCU** [comment]
This works for me. Thank you very much! 👏
