### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by OlympusMonds** [McYoloSwagHam/win3wm#8]
Hello,

Thanks for making this, I'm very appreciative. Don't be afraid to put up a GitHub sponsor link or similar :)

Could you please clarify what the difference between a 'move' and a 'carry' is? From my reading of the docs, I can't quite figure it out.

Thanks!

**Comment by McYoloSwagHam** [comment]
so a carry basically moves the current window and changes the monitor focus at the same time.

a move would just move a window to another monitor and keep your focus on the current monitor

**Comment by OlympusMonds** [comment]
Ah, great! I have just spent the last few minutes moving windows around, and now I wish I had been carrying them :)
