### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by willjp** [McYoloSwagHam/win3wm#9]
I'm hoping this saves some time for other people like me who are not super familiar with building software on windows.

Apologies if I missed a [component](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2019)

# Compilation Instructions

1. Download vs_community.exe for visualstudio 2019

https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=community&rel=16&utm_medium=microsoft&utm_source=docs.microsoft.com&utm_campaign=link+cta&utm_content=download+commandline+parameters+vs2019+rc

2. Install components required to build
```bash
vs_community.exe --passive ^
  --add Microsoft.VisualStudio.Workload.VCTools --installRecommended ^
  --add Microsoft.VisualStudio.Component.VC.CLI.Support ^
  --add Microsoft.VisualStudio.Component.Windows10SDK.19041
```

3. Open `x64 Native Tools Command Prompt for VS 2019`

4. git clone and build

```bash
cd C:\Users\you\Downloads
git clone https://github.com/McYoloSwagHam/win3wm
cd win3wm
./build.bat
```

5. Run
```bash
cd build\
./WinWM.exe
```

Thank you for writing this software!!

**Comment by McYoloSwagHam** [comment]
while most of the steps are right, I'd say open Developer Command Prompt for Visual Studio 2019 instead of x64 native tools command prompt.
Since you might not be building ForceResize86 and x86ipc since they are x86.

**Comment by McYoloSwagHam** [comment]
Added CI with files uploaded
